# Change these first
owner: perke # Your GitHub organization or username, where this repository lives
repo: bfnl-status # The name of this repository

sites:
  - name: Babilou Family Netherlands
    url: https://babilou-family.nl
  - name: BLOS
    url: https://www.blos.nl
  - name: Bijdehandjes
    url: https://www.bijdehandjes.info
  - name: Zonnekinderen
    url: https://www.zonnekinderen.nl
  - name: Zein Childcare
    url: https://www.zeinchildcare.nl
  - name: Speelschool
    url: https://www.speelschool.nl
    # rebuild

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.babilou-family.nl
  # baseUrl: /bfnl-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: BFNL Status
  introTitle: "Status of Babilou Family Netherlands digital systems"
  introMessage: 
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
